### PR TITLE
Fix ambiguity of std::begin/end

### LINKED ISSUE #39: Boost\libs\coroutine2 failed to build due to error C2668 on MSVC.
Issue description:
Boost\libs\coroutine2 failed to build due to error C2668 on MSVC. Could you please take a look? We ues  boostorg/boost@ea9f9fb from Boost master branch. from Boost master branch.

**Build step:**

1. git clone -c core.autocrlf=true --recursive ​https://github.com/boostorg/boost.git boost
2. open a VS 2019 x64 command prompt and browse to boost
3. .\bootstrap
4. .\b2 headers variant=release --build-dir=..\out\x64rel address-model=64
5. .\b2 variant=release --build-dir=..\out\x64rel address-model=64
6. .\b2 -j4 variant=release --build-dir=..\out\x64rel libs\coroutine2\test

**Error info:**
test_coroutine.cpp
libs\coroutine2\test\test_coroutine.cpp(538): error C2668: 'std::begin': ambiguous call to overloaded function
.\boost/coroutine2/detail/pull_coroutine.hpp(301): note: could be 'boost::coroutines2::detail::pull_coroutine<T>::iterator std::begin<T>(boost::coroutines2::detail::pull_coroutine<T> &)' [found using argument-dependent lookup]
        with
        [
            T=int
        ]
.\boost/coroutine2/detail/pull_coroutine.hpp(285): note: or       'boost::coroutines2::detail::pull_coroutine<T>::iterator boost::coroutines2::detail::begin<T>(boost::coroutines2::detail::pull_coroutine<T> &)' [found using argument-dependent lookup]
        with
        [
            T=int
        ]
libs\coroutine2\test\test_coroutine.cpp(539): note: while trying to match the argument list '(boost::coroutines2::detail::pull_coroutine<T>)'
        with
        [
            T=int
        ]
libs\coroutine2\test\test_coroutine.cpp(538): error C2668: 'std::end': ambiguous call to overloaded function
.\boost/coroutine2/detail/pull_coroutine.hpp(307): note: could be 'boost::coroutines2::detail::pull_coroutine<T>::iterator std::end<T>(boost::coroutines2::detail::pull_coroutine<T> &)' [found using argument-dependent lookup]
        with
        [
            T=int
        ]

### LINKED ISSUE #42: ambiguous call to begin end for coroutine<>::pull_type breaks range-based for (C++17 mode)
see #31

the change introduced now doesn't allow 

```C++
using namespace boost::coroutines2;

auto my_coro = coroutine<int>::pull_type{
    [](coroutine<int>::push_type& yield) {
        for (int i = 0; i < 5; ++i) {
            yield(i);
        }
    }
};

for (auto i : my_coro) {
                 // ^ ambiguous call to 'begin', ambiguous call to 'end'
    std::cout << i << std::endl;
}
```

tested with gcc 10.3.0, using --std=c++17; and msvc also using c++17 mode

using boost 1.76.0

see also  #39

### PR DESCRIPTION
**Pull request by hp-peti**
- this patch should restore the range-based for functionality for pull-type coroutines
fixes #39 
fixes #42

### CODE REVIEW

File: include/boost/coroutine2/detail/pull_coroutine.hpp [hunk 1]
```diff
@@ -296,17 +296,8 @@ end( pull_coroutine< T > &) {
...
-    return boost::coroutines2::detail::begin( c);
-}
-
-template< typename T >
-typename boost::coroutines2::detail::pull_coroutine< T >::iterator
-end( boost::coroutines2::detail::pull_coroutine< T > & c) {
-    return boost::coroutines2::detail::end( c);
-}
+using boost::coroutines2::detail::begin;
+using boost::coroutines2::detail::end;
```
Comment (jwakely) [inline include/boost/coroutine2/detail/pull_coroutine.hpp:300]: This is still undefined behaviour. You cannot add declarations to namespace `std`.

What are the (undefined) overloads of `std::begin` and `std::end` trying to achieve? To ensure that qualified calls to `std::begin` and `std::end` will use the customized boost ones? Don't do that.

If you want `std::begin` and `std::end` to be valid for a `pull_coroutine` (because it is meant to be container-like) then add `pull_coroutine::begin()` and `pull_coroutine::end()` member functions. If it's not meant to be container-like, then `std::begin(coro)` and `std::end(coro)` should not work with it (since they are constrained to call `coro.begin()` and `coro.end()` respectively).

Comment (jwakely) [reply include/boost/coroutine2/detail/pull_coroutine.hpp:300]: Alternatively, just remove these undefined declarations completely. Require users to use unqualified `begin(coro)` and `end(coro)` calls, which will find the overloads in `boost::coroutines2::detail` using ADL.

Comment (jwakely) [reply include/boost/coroutine2/detail/pull_coroutine.hpp:300]: > I mostly agree but see #31

So fix the docs :shrug: 

That's why I asked about the intended API above. If the point is just to enable range-based `for` then the undefined overloads are not needed. If being able to call `std::begin(coro)` is essential for some reason (even if that's just because it has been documented as supported) then add `coro.begin()` and `coro.end()` member functions, so that the generic `std::begin` and `std::end` can use them. The docs would be lying (they aren't "overloaded") but calling `std::begin(coro)` would still  work, and do the same thing as before. Just without undefined behaviour.

>  I think specializing std::begin/std::end for user-defined types is accepted though.

Yes, but those function templates are not specializations, they are overloads, which are not allowed. And specializing is a bad idea even if it's allowed. http://www.gotw.ca/publications/mill17.htm

Adding names to `std` via a using-declaration is not allowed though, so the change in this PR is still undefined behaviour.

> Also the patch above is backwards compatible with the already released sources (it might not need to be).

But still undefined behaviour.

Comment (hp-peti) [reply include/boost/coroutine2/detail/pull_coroutine.hpp]: Thank you for the extensive clarification.

Please note the modified pull request which defines .begin and .end members, eliminating the need for new definitions in the std namespace.

**Comment by hp-peti** [comment]
@olk could you take a look at this?

**Comment by olk** [comment]
ty
